services:
  hass-agent-bot:
    image: dmansurov83/hass-agent-bot:latest
    container_name: hass-agent-bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - APP_VERSION=${APP_VERSION:-0.1.0}
      - HA_URL=${HA_URL}
      - HA_TOKEN=${HA_TOKEN}
      - TG_TOKEN=${TG_TOKEN}
      - ALLOW_USERS=${ALLOW_USERS}
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
      - DATA_DIR=/data
    volumes:
      # config.yaml — ФАЙЛ, не папка
      - ./config.yaml:/config.yaml:ro
      # персистентность таймеров
      - ./data:/data
    command: ["--config", "/config.yaml"]